name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Entering Jobs!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Setting up Node JS"

     
