name: Build AMI and Include Artifact

on: [push]

jobs:
  build_ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Repository Zip file creation
      run: |
        mkdir -p zip
        git archive --format=zip HEAD -o zip/webapp.zip
        ls -l zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp-zip
        path: zip/webapp.zip
