name: Build AMI and Include Artifact

on: [push]

jobs:
  build_ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Repository Zip file creation
      run: |
        mkdir -p zip
        git archive --format=zip HEAD -o zip/webapp.zip
        ls -l zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp-zip
        path: zip/webapp.zip

    - name: Verify ZIP file
      run: |
        ls -l zip
        if [ -f "zip/webapp.zip" ]; then
          echo "ZIP file exists."
        else
          echo "ZIP file does not exist."
        exit 1
        fi

    - name: Validate Packer Configuration
      run: |
          echo "Validating Packer configuration..."
          if packer validate packer/aws-ami.pkr.hcl; then
            echo "Packer configuration is valid."
          else
            echo "Packer configuration validation failed."
            exit 1
          fi

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: 1.9.4 

    - name: Configure AWS Credentials and build packer
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AMI_AWS_REGION }}

    - name: Packer Init
      run: packer init packer/aws-ami.pkr.hcl

    - name: Packer Build
      run: |
        packer build packer/aws-ami.pkr.hcl
