name: Build AMI and Include Artifact

on: [push]

env:
  HOST: "localhost"
  MYSQLUSER: "root"
  PASSWORD: ${{ secrets.SQL_PASSWORD }}

jobs:
  build_ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Node JS message
        run: echo "Setting up Node JS"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Finishing Node JS set up message
        run: echo "Node JS installation done"

      - name: Starting installation for mysql-server
        run: echo "mysql-server installation done"

      - name: configuremysql
        run: |
          sudo apt-get update
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u root -p"${PASSWORD}" -e "CREATE DATABASE Assignments_Demo_DB;"

      - name: Starting dependency installation
        run: echo "Installing Dependencies"

      - name: Install dependencies
        run: npm install

      - name: Dependency installation completed
        run: echo "Dependencies Installed"

      - name: Running test files
        run: echo "Starting test"

      - name: run tests
        run: npm test

      - name: Zip the artifact
        run: |
          zip -r webapp.zip ./
          ls -lrth

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: webapp.zip

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AMI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AMI_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AMI_AWS_REGION }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer Init
        run: packer init packer/aws-ami.pkr.hcl

      - name: Packer Build and create ami_id.txt
        id: packer_build
        run: |
          packer build -on-error=cleanup -color=false -var-file=packer/packer-config.hcl packer/aws-ami.pkr.hcl | tee packer_output.log
          ami_id=$(grep -oE 'ami-[a-f0-9]+' packer_output.log | awk '{sub(/^\*\*\*/, "", $NF); print $NF}')
          echo "AMI_ID is: $ami_id"
          echo "AMI_ID=$ami_id" > ami_id.txt

      - name: Set up AWS CLI for dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AMI_AWS_REGION }}

      - name: Update Launch Template with new AMI ID
        run: |
          cat ami_id.txt | while read file; do
            aws ec2 create-launch-template-version \
              --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }} \
              --version-description latest \
              --source-version 1 \
              --launch-template-data "ImageId=$file"
          done

      - name: Update Launch Template with new AMI ID
        run: |
          launch_template_id=$(aws ec2 describe-launch-templates --launch-template-name csye6225-launch-template --region ${{ secrets.AMI_AWS_REGION }} --query 'LaunchTemplates[0].LaunchTemplateId' --output json)

          if [ -z "$launch_template_id" ]; then
            echo "Error: Launch template ID not found or empty. Exiting."
            exit 1
          fi

          echo "Launch Template ID: $launch_template_id"

          launch_template_id=$(echo "$launch_template_id" | tr -d '"')

          echo "Launch Template ID without quotes: $launch_template_id"

          ami_id="${{ steps.get_ami_id.outputs.ami_id }}"

          echo "AMI ID from step: ${{ steps.get_ami_id.outputs.ami_id }}"

          echo "AMI ID after assigning: $ami_id"

          if [ -z "$ami_id" ]; then
            echo "Error: AMI ID not found or empty. Exiting."
            exit 1
          fi

          echo "AMI ID: $ami_id"

          aws ec2 create-launch-template-version \
            --launch-template-name "${{ secrets.LAUNCH_TEMPLATE_NAME }}" \
            --source-version 1 \
            --launch-template-data "{\"ImageId\":\"$ami_id\"}"

      - name: Refresh autoscaling group
        run: |
          asg_name=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
          echo "Autoscaling group name: $asg_name"
          aws autoscaling start-instance-refresh --auto-scaling-group-name $asg_name
