name: Check Packer File Formatting and Validation

on:
  push: {}

jobs:
  packer-format-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@latest
        with:
          version: 1.9.4  # Replace with your desired Packer version

      - name: Clear Packer Plugin Cache
        run: packer plugin clear

      - name: Debugging Information
        run: |
          packer version
          env | sort  

      - name: Packer Init
        run: packer init

      - name: Starting Packer Formatting Check
        run: echo "Packer Formatting check starts"

      - name: Check Packer File Formatting
        run: |
          # Run 'packer fmt' and capture the output
          fmt_output=$(packer fmt -check .)

          # Check if there is any output from 'packer fmt'
          if [ -n "$fmt_output" ]; then
            echo "Packer file is not properly formatted. Please run 'packer fmt' to format it."
            echo "Formatting issues found:"
            echo "$fmt_output"
            exit 1  # Fail the workflow
          else
            echo "Packer file is properly formatted."
          fi

      - name: Starting Packer Validation Check
        run: echo "Packer Validation starts"

      - name: Validate Packer Configuration
        run: ./validate-packer.sh

