name: Workflow Test

on: [push]

env:
  HOST: "localhost"
  MYSQLUSER: "root"
  PASSWORD: ""

jobs:
  push-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Hello Message
      run: echo "Hello, GitHub Actions!"

    - name: Statring Node JS message
      run: echo "Setting up Node JS"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install MySQL
      run: |
          echo "Installing MySQL server"
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start

    - name: Generate Random Password
      id: generate-password
      run: echo "::set-output name=password::$(openssl rand -base64 12)"

    - name: Set MySQL Root Password
      run: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ steps.generate-password.outputs.password }}';"

    - name: Store Password in GitHub Secret
      run: echo "::add-mask::${{ steps.generate-password.outputs.password }}"

    - name: Wait for MySQL to start
      run: |
          until mysqladmin ping -h ${{ env.HOST }} -u ${{ env.MYSQLUSER }} -p${{ secrets.MY_GENERATED_PASSWORD }}; do
            echo "Waiting for MySQL to start..."
            sleep 5
          done

    - name: Install MySQL client
      run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

    - name: Finishing Node JS set up message
      run: echo "Node JS installation done"

    - name: Starting dependency installation
      run: echo "Installing Dependencies"

    - name: Install dependencies
      run: npm install

    - name: Dependency installation completed
      run: echo "Dependencies Installed"

    - name: Running test files
      run: echo "Starting test"

    - name: Show environment variables
      run: |
        echo "HOST=${HOST}"
        echo "MYSQLUSER=${MYSQLUSER}"
        echo "PASSWORD=${{ secrets.MY_GENERATED_PASSWORD }}"

    - name: Run MySQL Ping
      run: |
          mysqladmin ping -h ${{ env.HOST }} -u ${{ env.MYSQLUSER }} -p${{ secrets.MY_GENERATED_PASSWORD }}

    - name: run tests
      run: npm test

    - name: Test files execution completion
      run: echo "Finished running test files"
